services:
  - type: web
    name: medimart
    env: docker
    dockerfilePath: ./Dockerfile
    branch: main # Change this to your main branch name if different
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: medimart
          type: web
          property: url
      - key: DB_CONNECTION
        value: pgsql # Render provides PostgreSQL by default
    buildCommand: "" # No need as it's handled in the Dockerfile
    startCommand: "" # No need as it's handled in the Dockerfile

databases:
  - name: medimart_db
    databaseName: medimart
    ipAllowList: [] # Allow all IPs
