services:
  - type: web
    name: medimart
    env: docker
    dockerfilePath: ./Dockerfile
    branch: deploy # Change this to your main branch name if different
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: medimart
          type: web
          property: url
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
    buildCommand: "" # No need as it's handled in the Dockerfile
    startCommand: "" # No need as it's handled in the Dockerfile

