services:
  - type: web
    name: medimart
    env: docker
    dockerfilePath: ./Dockerfile
    branch: deploy # Change this to your main branch name if different
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: medimart
          type: web
          property: url
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d0hmra3uibrs739tcfsg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: project_medimart
      - key: DB_USERNAME
        value: project_medimart_user
      - key: DB_PASSWORD
        value: STZbIrBLksHHw5OtIsnCgVmilITrWTKC
    buildCommand: "" # No need as it's handled in the Dockerfile
    startCommand: "" # No need as it's handled in the Dockerfile

